language: csharp
mono: none
dotnet: 3.1.202
solution: WebRtcVadSharp.sln
install:
  - dotnet restore
script:
  - msbuild /p:Configuration=Release WebRtcVadSharp.sln
  - dotnet build
  - dotnet test WebRtcVadSharp.Tests/bin/Release/netcoreapp3.1/WebRtcVadSharp.Tests.dll