os: windows
language: cpp
solution: WebRtcVadSharp.sln
env:
  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
install:
  - choco install dotnetcore-sdk
  - dotnet restore
script:
  #- export PATH=$MSBUILD_PATH:$PATH
  #- ./build.bat
  - MSBuild.exe //p:Configuration=Release WebRtcVadSharp.sln
  - dotnet build --configuration Release
  - dotnet test WebRtcVadSharp.Tests/bin/Release/netcoreapp3.1/WebRtcVadSharp.Tests.dll