os: windows
language: cpp
solution: WebRtcVadSharp.sln
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
install:
  - choco install visualstudio2019buildtools
  - choco install dotnetcore-sdk
  - dotnet restore
script:
  - ls -lR "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe //p:Configuration=Release WebRtcVad/WebRtcVad.vcxproj
  - dotnet build --configuration Release
  - dotnet test WebRtcVadSharp.Tests/bin/Release/netcoreapp3.1/WebRtcVadSharp.Tests.dll
